### PR TITLE
add satisfies option to column

### PR DESCRIPTION
**Pull request by rudolph-miller**
made slot to be able to take funcallable object with `:satisfies` option.
You can check valid or not with `valid-p` method.

### CODE REVIEW

**Comment by rudolph-miller** [comment]
#30 @pocket7878
With this feature, you can check valid or not like

``` Lisp
(defmethod insert-dao :around ((object <dao-class>))
  (if (valid-p object) (call-next-method) nil))
```

**Comment by pocket7878** [comment]
@Rudolph-Miller 
Wow! This looks so nice. But why not call validate-p by default?

**Comment by rudolph-miller** [comment]
Validator can return `nil` and also can raise `error` with invalid value. When people set validator to raise `error` as `:satisfies`, with implicitly calling `valid-p` in `insert-dao`, `update-dao` or `select-dao`, it'll be hard to handle `condition`. With explicitly calling, people can handle `condition` easily and it's simple. WHEN and WHERE validation should be called depends on user.

**Comment by pocket7878** [comment]
Thank you for your reply! I understand.

**Comment by fukamachi** [comment]
Thanks for the great feature! :+1: :sparkles:

**Pull request merged**
