### PR TITLE
Validation before save.

### PR DESCRIPTION
**Pull request by pocket7878**
Add "validations" slots to <dao-table-class> with built-in shortcut validation functions.
User can add validation before {insert | update}-dao.

### CODE REVIEW

**Comment by fukamachi** [comment]
Thank you for the great contribution!

I'd like to ask something:
- The default behaviour of `insert-dao` and `update-dao` when the validation has failed is just ignoring?
  - Isn't it confusing?
- Why not just adding `:before` method?
- Is it possible to make the validation feature an individual library?

**Comment by fukamachi** [comment]
BTW, have you seen this library? https://github.com/mmontone/clavier
It's quite new and is going to be included in Quicklisp this month.

**Comment by fukamachi** [comment]
CC @Rudolph-Miller

**Comment by pocket7878** [comment]
Currently I just ignoring when validation is failed.
In Rails's ActiveRecord default behavior of validation-failure is just ignoring them (return false).
Rails also has banged-crud-method(e.g save!) which throws exception when the validation has failed.
So should I add same methods to user can handle validation-failure?

When the validations has failed I want to just ignoring them, so I added :around method to interrupt base method calling.

clavier is look so great :smile: 

Well, on second thought, it might be better separate validations to library to add validation dynamically.
Thank you for your advice!

**Pull request closed without merging**
