### PR TITLE
Nicer generate defclass api

### PR DESCRIPTION
**Pull request by rudolph-miller**
- generate defclass by class-name and :table-name(optional) like just  
  `(generate-defclass 'user :table-name "users")`.

### CODE REVIEW

**Comment by fukamachi** [comment]
I assume you wanna generate a defclass form from a table-name string.
If so, just allowing a table name in `generate-defclass` would be better.

**Comment by rudolph-miller** [comment]
Actually, no. I wanna `generate-defclass` with just symbol before creating class.

**Comment by fukamachi** [comment]
Hm, okay. Then the `table-name` feature is redundant and it doesn't look any "nicer" at all to me.

**Comment by rudolph-miller** [comment]
Often people want to create class `user` with table-name `users`, I think.
And, actually I wanna create class `advertiser` with `advertisers` just using `(generate-defclass 'advertiser :table-name "advertisers") without creating class`advertisers` before generating.

**Pull request merged**
